name: lifeguardian
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  google_mlkit_pose_detection: ^0.14.1
  google_mlkit_object_detection: ^0.15.1
  permission_handler: ^11.3.1
  equatable: ^2.0.5
  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  crypto: ^3.0.3
  fl_chart: ^1.1.1
  image_picker: ^1.2.1
  google_mlkit_commons: ^0.11.1
  google_fonts: ^8.0.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  video_player: ^2.9.1
  screenshot: ^3.0.0
  path_provider: ^2.1.3
  gal: ^2.3.2
  image_cropper: ^8.0.2
  shared_preferences: ^2.3.5
  table_calendar: ^3.2.0
  lucide_icons: ^0.257.0
  rxdart: ^0.28.0
  email_otp: ^3.1.0
  cloud_functions: ^5.6.2
  flutter_secure_storage: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_full.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon_full.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
